### PR TITLE
Add RadxaRock4SE

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by msgilligan** [comment]
I tested Rock 4SE with kernel 6.11. I'm going to update the Radxa boards to 6.12 and re-test.

**Comment by RadxaYuntian** [comment]
I got ROCK 4C+ running 6.12.1 with bcachefs root today so the latest kernel should work without issue:

img_v3_02h7_452baadd-3746-4a34-b5e1-d7d229bf357g

I also found that when using systemd-boot instead of extlinux boot, since sd-boot's EFI bootloader is small, I don't need to hack U-Boot at all to get kernel booting. So cross building an EFI image is my focus now instead of fixing U-Boot.

**Comment by msgilligan** [comment]
@RadxaYuntian I'm focused on U-Boot partly because I am working with OP-TEE on the Rock 4 and their reference build uses U-Boot.

**Comment by RadxaYuntian** [comment]
This documentation might be helpful about OP-TEE: https://docs.radxa.com/en/template/sbc/low-level-dev/rk_anti_copy_board

**Comment by msgilligan** [comment]
> This documentation might be helpful about OP-TEE: https://docs.radxa.com/en/template/sbc/low-level-dev/rk_anti_copy_board

Thank you!

**Review by asonix — APPROVED** [review]

**Pull request merged**
